apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-master
  labels:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: master
spec:
  serviceName: {{ .Release.Name }}-master
  replicas: {{ .Values.master.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: seaweedfs
      app.kubernetes.io/component: master
  template:
    metadata:
      labels:
        app.kubernetes.io/name: seaweedfs
        app.kubernetes.io/component: master
    spec:
      containers:
        - name: master
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["weed", "master", "-port={{ .Values.master.port }}", "-defaultReplication=000"]
          ports:
            - containerPort: {{ .Values.master.port }}
              name: master
          resources:
            {{- toYaml .Values.master.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-master
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.master.port }}
      targetPort: master
      name: master
  selector:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: master
