{{- if .Values.s3.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-s3-credentials
  labels:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: s3
type: Opaque
stringData:
  accessKey: {{ .Values.s3.accessKey | quote }}
  secretKey: {{ .Values.s3.secretKey | quote }}
  s3.json: |
    {
      "identities": [
        {
          "name": "admin",
          "credentials": [
            {
              "accessKey": {{ .Values.s3.accessKey | quote }},
              "secretKey": {{ .Values.s3.secretKey | quote }}
            }
          ],
          "actions": ["Admin", "Read", "Write", "List", "Tagging"]
        }
      ]
    }
{{- end }}
