apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-volume
  labels:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: volume
spec:
  serviceName: {{ .Release.Name }}-volume
  replicas: {{ .Values.volume.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: seaweedfs
      app.kubernetes.io/component: volume
  template:
    metadata:
      labels:
        app.kubernetes.io/name: seaweedfs
        app.kubernetes.io/component: volume
    spec:
      containers:
        - name: volume
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - weed
            - volume
            - -port={{ .Values.volume.port }}
            - -mserver={{ .Release.Name }}-master:{{ .Values.master.port }}
            - -dir={{ .Values.volume.dataDir }}
          ports:
            - containerPort: {{ .Values.volume.port }}
              name: volume
          volumeMounts:
            - name: data
              mountPath: {{ .Values.volume.dataDir }}
          resources:
            {{- toYaml .Values.volume.resources | nindent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.volume.storage.storageClass }}
        storageClassName: {{ .Values.volume.storage.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.volume.storage.size }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-volume
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.volume.port }}
      targetPort: volume
      name: volume
  selector:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: volume
