apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-openldap
  labels:
    app.kubernetes.io/name: openldap
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  adminPassword: {{ .Values.adminPassword | quote }}
  configPassword: {{ .Values.configPassword | quote }}
