{{- if .Values.s3.endpoint }}
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: {{ include "pgaas.clusterName" . }}-scheduled-backup
  labels:
    {{- include "pgaas.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.backup.schedule | quote }}
  backupOwnerReference: self
  cluster:
    name: {{ include "pgaas.clusterName" . }}
  target: {{ .Values.backup.target }}
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
    parameters:
      barmanObjectName: {{ include "pgaas.clusterName" . }}-object-store
  {{- if .Values.backup.retentionPolicy }}
  retentionPolicy: {{ .Values.backup.retentionPolicy | quote }}
  {{- end }}
{{- end }}
